name: ESP32-S3 Build and Release

on:
  push:
    tags:
      - "v*"   # v1.0.0 のようなタグが push されたら実行

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run --environment esp32-s3-wroom-1

      - name: Upload firmware to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: .pio/build/esp32-s3-wroom-1/firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
